services:
  - type: web
    name: expense-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    rootDir: .
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_ENV
        value: "production"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "15"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: GUEST_ACCESS_MIN
        value: "60"
      - key: GUEST_REFRESH_DAYS
        value: "1"
      - key: FRONTEND_URL
        value: "https://expense-frontend.onrender.com"
      - key: EMAIL_FROM
        value: "no-reply@example.com"
    buildCommand: ""
    startCommand: ""

  - type: web
    name: expense-frontend
    runtime: static
    buildCommand: cd expense-ui && npm install && npm run build
    staticPublishPath: ./expense-ui/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://expense-backend.onrender.com/api"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

